import { afterAll, afterEach, beforeAll, beforeEach, describe, expect, it } from "vitest";
import { setupServer } from "msw/node";

import { mockSignIn } from "@/mocks/auth";
import {
  resetMockCollectivitySubscription,
  seedMockCollectivityInvitationClaim,
} from "@/mocks/collectivity-subscription";
import { collectivityHandlers } from "@/mocks/handlers/collectivity";

const origin = "http://localhost:1337";
const server = setupServer(...collectivityHandlers);

function headers(identifier = "demo@example.com") {
  const session = mockSignIn({ identifier, password: "123" });
  return { Authorization: `Bearer ${session.access_token}` };
}

describe.sequential("collectivity invitation mock", () => {
  beforeAll(() => server.listen({ onUnhandledRequest: "error" }));
  beforeEach(() => resetMockCollectivitySubscription());
  afterEach(() => server.resetHandlers());
  afterAll(() => server.close());

  it("serves safe invitation preview states without exposing the token", async () => {
    const response = await fetch(
      `${origin}/api/collectivity/subscription-invitations/preview?token=mock-invitation-valid`
    );
    expect(response.status).toBe(200);
    await expect(response.json()).resolves.toEqual(
      expect.objectContaining({
        data: expect.objectContaining({
          state: "valid",
          inviter: expect.objectContaining({
            firstName: "Claire",
            organization: expect.any(String),
          }),
        }),
      })
    );

    const expired = await fetch(
      `${origin}/api/collectivity/subscription-invitations/preview?token=mock-invitation-expired`
    );
    await expect(expired.json()).resolves.toEqual(
      expect.objectContaining({ data: expect.objectContaining({ state: "expired" }) })
    );
  });

  it("creates a pending request and recovers its claim id on a duplicate request", async () => {
    const request = () =>
      fetch(`${origin}/api/collectivity/subscription-claims`, {
        method: "POST",
        headers: { ...headers(), "Content-Type": "application/json" },
        body: JSON.stringify({ token: "mock-invitation-valid" }),
      });
    const first = await request();
    const payload = (await first.json()) as { data: { id: number; status: string } };
    expect(payload.data.status).toBe("pending");

    const duplicate = await request();
    expect(duplicate.status).toBe(409);
    await expect(duplicate.json()).resolves.toEqual(
      expect.objectContaining({
        error: expect.objectContaining({
          details: expect.objectContaining({
            code: "CLAIM_ALREADY_EXISTS",
            claimId: payload.data.id,
          }),
        }),
      })
    );
  });

  it("accepts the exact invitation token generated by the subscription mock for another user", async () => {
    const ownerHeaders = headers("subTest@example.com");
    const createLink = await fetch(`${origin}/api/collectivity/subscriptions/9001/claim-link`, {
      method: "POST",
      headers: ownerHeaders,
    });
    const link = (await createLink.json()) as { data: { token: string } };

    const preview = await fetch(
      `${origin}/api/collectivity/subscription-invitations/preview?${new URLSearchParams({ token: link.data.token })}`
    );
    expect(preview.status).toBe(200);

    const recipientHeaders = headers("collectivity.no-inventory@example.com");
    const request = await fetch(`${origin}/api/collectivity/subscription-claims`, {
      method: "POST",
      headers: { ...recipientHeaders, "Content-Type": "application/json" },
      body: JSON.stringify({ token: link.data.token }),
    });
    const requestPayload = (await request.json()) as { data: { id: number; status: string } };
    expect(requestPayload).toEqual(
      expect.objectContaining({ data: expect.objectContaining({ status: "pending" }) })
    );

    const ownerDetail = await fetch(`${origin}/api/collectivity/subscriptions/9001`, {
      headers: ownerHeaders,
    });
    await expect(ownerDetail.json()).resolves.toEqual(
      expect.objectContaining({
        data: expect.objectContaining({
          assignments: expect.arrayContaining([
            expect.objectContaining({
              claimantEmail: "collectivity.no-inventory@example.com",
              status: "pending",
            }),
          ]),
        }),
      })
    );

    const approve = await fetch(
      `${origin}/api/collectivity/subscriptions/9001/claims/${requestPayload.data.id}/approve`,
      { method: "POST", headers: ownerHeaders }
    );
    expect(approve.status).toBe(200);

    const recipientClaim = await fetch(
      `${origin}/api/collectivity/subscription-claims/${requestPayload.data.id}`,
      { headers: recipientHeaders }
    );
    await expect(recipientClaim.json()).resolves.toEqual(
      expect.objectContaining({ data: expect.objectContaining({ status: "approved" }) })
    );

    const available = await fetch(`${origin}/api/collectivity/subscription-claims/available`, {
      headers: recipientHeaders,
    });
    await expect(available.json()).resolves.toEqual(
      expect.objectContaining({
        data: [expect.objectContaining({ id: requestPayload.data.id, source: "invite_link" })],
      })
    );

    const init = await fetch(`${origin}/api/collectivity/projects/init`, {
      method: "POST",
      headers: { ...recipientHeaders, "Content-Type": "application/json" },
      body: JSON.stringify({
        approvedClaimId: requestPayload.data.id,
        name: "Projet de démonstration",
        slug: "projet-demonstration",
        territory: "Sfax",
        country: "TUN",
        referenceYear: 2024,
        inventoryYears: [2024],
        applicability: { airport: false, port: false, agriculture: true },
      }),
    });
    expect(init.status).toBe(200);

    const consumed = await fetch(
      `${origin}/api/collectivity/subscription-claims/${requestPayload.data.id}`,
      { headers: recipientHeaders }
    );
    await expect(consumed.json()).resolves.toEqual(
      expect.objectContaining({ data: expect.objectContaining({ status: "consumed" }) })
    );

    const availableAfterInit = await fetch(
      `${origin}/api/collectivity/subscription-claims/available`,
      { headers: recipientHeaders }
    );
    await expect(availableAfterInit.json()).resolves.toEqual({ data: [] });
  });

  it("serves approved, consumed, denied, and revoked recipient states", async () => {
    const approved = seedMockCollectivityInvitationClaim("approved");
    const consumed = seedMockCollectivityInvitationClaim("consumed");
    const denied = seedMockCollectivityInvitationClaim("denied");
    const revoked = seedMockCollectivityInvitationClaim("revoked");
    const auth = headers();
    for (const claim of [approved, consumed, denied, revoked]) {
      const response = await fetch(`${origin}/api/collectivity/subscription-claims/${claim.id}`, {
        headers: auth,
      });
      const payload = (await response.json()) as { data: { status: string } };
      expect(payload.data.status).toBe(claim.status);
    }
  });
});
